name: First WorkFlow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and Read Files
          run: |
            echo "My first GitHub Action Job"
            ls -lrta
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragron "Run, I'm a dragon" >> dragon.txt     
        #- name: List Files
        #  run: ls

        #- name: Read readme file
        #  run:  cat README.md

