name: Generate ASCII Artwork

on: push

jobs:
    ascii_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run, I'm a dragon" >> dragon.txt  
        
        - name: Test File Exists
          run: |
           ls
           cat dragon.txt
           grep -i "dragon" dragon.txt
        
          